env:
  browser: true
  es2021: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  require-jsdoc: warn
  max-len:
    - 2
    - 120
    - 4
  new-cap: 0